//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synox.Services.ServiceSMS.Entity.ServiceSIM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.m2mfrance.fr/", ConfigurationName="ServiceSIM.ServiceSIMSoap")]
    public interface ServiceSIMSoap {
        
        // CODEGEN: Generating message contract since message GetICCIDFromGsmNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://services.m2mfrance.fr/GetICCIDFromGsmNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberResponse GetICCIDFromGsmNumber(Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.m2mfrance.fr/")]
    public partial class SoapHeaderAuthentification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private string complementField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
                this.RaisePropertyChanged("Complement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetICCIDFromGsmNumber", WrapperNamespace="http://services.m2mfrance.fr/", IsWrapped=true)]
    public partial class GetICCIDFromGsmNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://services.m2mfrance.fr/")]
        public Synox.Services.ServiceSMS.Entity.ServiceSIM.SoapHeaderAuthentification SoapHeaderAuthentification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.m2mfrance.fr/", Order=0)]
        public string gsmNumber;
        
        public GetICCIDFromGsmNumberRequest() {
        }
        
        public GetICCIDFromGsmNumberRequest(Synox.Services.ServiceSMS.Entity.ServiceSIM.SoapHeaderAuthentification SoapHeaderAuthentification, string gsmNumber) {
            this.SoapHeaderAuthentification = SoapHeaderAuthentification;
            this.gsmNumber = gsmNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetICCIDFromGsmNumberResponse", WrapperNamespace="http://services.m2mfrance.fr/", IsWrapped=true)]
    public partial class GetICCIDFromGsmNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.m2mfrance.fr/", Order=0)]
        public string GetICCIDFromGsmNumberResult;
        
        public GetICCIDFromGsmNumberResponse() {
        }
        
        public GetICCIDFromGsmNumberResponse(string GetICCIDFromGsmNumberResult) {
            this.GetICCIDFromGsmNumberResult = GetICCIDFromGsmNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSIMSoapChannel : Synox.Services.ServiceSMS.Entity.ServiceSIM.ServiceSIMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSIMSoapClient : System.ServiceModel.ClientBase<Synox.Services.ServiceSMS.Entity.ServiceSIM.ServiceSIMSoap>, Synox.Services.ServiceSMS.Entity.ServiceSIM.ServiceSIMSoap {
        
        public ServiceSIMSoapClient() {
        }
        
        public ServiceSIMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSIMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSIMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSIMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberResponse Synox.Services.ServiceSMS.Entity.ServiceSIM.ServiceSIMSoap.GetICCIDFromGsmNumber(Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberRequest request) {
            return base.Channel.GetICCIDFromGsmNumber(request);
        }
        
        public string GetICCIDFromGsmNumber(Synox.Services.ServiceSMS.Entity.ServiceSIM.SoapHeaderAuthentification SoapHeaderAuthentification, string gsmNumber) {
            Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberRequest inValue = new Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberRequest();
            inValue.SoapHeaderAuthentification = SoapHeaderAuthentification;
            inValue.gsmNumber = gsmNumber;
            Synox.Services.ServiceSMS.Entity.ServiceSIM.GetICCIDFromGsmNumberResponse retVal = ((Synox.Services.ServiceSMS.Entity.ServiceSIM.ServiceSIMSoap)(this)).GetICCIDFromGsmNumber(inValue);
            return retVal.GetICCIDFromGsmNumberResult;
        }
    }
}
