<?xml version="1.0" encoding="utf-8"?><Database Name="SMS_DB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GUILLAUME-PC\SQL_SERVER_SYNOX;Initial Catalog=SMS_DB;Integrated Security=True" SettingsObjectName="ServiceSMS.Properties.Settings" SettingsPropertyName="SMS_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Message" Member="Message">
    <Type Name="Message">
      <Column Name="idMessage" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="messageTexte" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="messagePDU" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="accuseReception" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="noDestinataire" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="noEmetteur" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEncodage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idStatut" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Message_MessageEnvoi" Member="MessageEnvoi" ThisKey="idMessage" OtherKey="idMessage" Type="MessageEnvoi" Cardinality="One" />
      <Association Name="Message_MessageRecu" Member="MessageRecu" ThisKey="idMessage" OtherKey="idMessage" Type="MessageRecu" Cardinality="One" />
      <Association Name="Statut_Message" Member="Statut" ThisKey="idStatut" OtherKey="idStatut" Type="Statut" IsForeignKey="true" />
      <Association Name="Encodage_Message" Member="Encodage" ThisKey="idEncodage" OtherKey="idEncodage" Type="Encodage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageEnvoi" Member="MessageEnvoi">
    <Type Name="MessageEnvoi">
      <Column Name="idMessage" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dureeValidite" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="dateDemande" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dateEnvoi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Message_MessageEnvoi" Member="Message" ThisKey="idMessage" OtherKey="idMessage" Type="Message" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageRecu" Member="MessageRecu">
    <Type Name="MessageRecu">
      <Column Name="idMessage" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dateReception" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dateLecture" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Message_MessageRecu" Member="Message" ThisKey="idMessage" OtherKey="idMessage" Type="Message" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Statut" Member="Statut">
    <Type Name="Statut">
      <Column Name="idStatut" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="libelleStatut" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Statut_Message" Member="Message" ThisKey="idStatut" OtherKey="idStatut" Type="Message" />
    </Type>
  </Table>
  <Table Name="dbo.Encodage" Member="Encodage">
    <Type Name="Encodage">
      <Column Name="idEncodage" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="libelleEncodage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Encodage_Message" Member="Message" ThisKey="idEncodage" OtherKey="idEncodage" Type="Message" />
    </Type>
  </Table>
</Database>