//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.239
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SMS_DBModel", "FK_Message_Encodage", "Encodage", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServiceSMS.Encodage), "Message", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServiceSMS.Message))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SMS_DBModel", "FK_Message_Statut", "Statut", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServiceSMS.Statut), "Message", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServiceSMS.Message))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SMS_DBModel", "FK_MessageEnvoi_Message", "Message", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServiceSMS.Message), "MessageEnvoi", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ServiceSMS.MessageEnvoi))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SMS_DBModel", "FK_MessageRecu_Message", "Message", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServiceSMS.Message), "MessageRecu", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ServiceSMS.MessageRecu))]

// Nom du fichier d'origine :
// Date de génération : 09/01/2012 15:31:32
namespace ServiceSMS
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBEntities dans le schéma.
    /// </summary>
    public partial class SMS_DBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initialise un nouvel objet SMS_DBEntities à l'aide de la chaîne de connexion trouvée dans la section « SMS_DBEntities » du fichier de configuration d'application.
        /// </summary>
        public SMS_DBEntities() : 
                base("name=SMS_DBEntities", "SMS_DBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet SMS_DBEntities.
        /// </summary>
        public SMS_DBEntities(string connectionString) : 
                base(connectionString, "SMS_DBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet SMS_DBEntities.
        /// </summary>
        public SMS_DBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SMS_DBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Il n'existe aucun commentaire pour Encodage dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Encodage> Encodage
        {
            get
            {
                if ((this._Encodage == null))
                {
                    this._Encodage = base.CreateQuery<Encodage>("[Encodage]");
                }
                return this._Encodage;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Encodage> _Encodage;
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Message> Message
        {
            get
            {
                if ((this._Message == null))
                {
                    this._Message = base.CreateQuery<Message>("[Message]");
                }
                return this._Message;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Message> _Message;
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageEnvoi dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<MessageEnvoi> MessageEnvoi
        {
            get
            {
                if ((this._MessageEnvoi == null))
                {
                    this._MessageEnvoi = base.CreateQuery<MessageEnvoi>("[MessageEnvoi]");
                }
                return this._MessageEnvoi;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<MessageEnvoi> _MessageEnvoi;
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageRecu dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<MessageRecu> MessageRecu
        {
            get
            {
                if ((this._MessageRecu == null))
                {
                    this._MessageRecu = base.CreateQuery<MessageRecu>("[MessageRecu]");
                }
                return this._MessageRecu;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<MessageRecu> _MessageRecu;
        /// <summary>
        /// Il n'existe aucun commentaire pour Statut dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Statut> Statut
        {
            get
            {
                if ((this._Statut == null))
                {
                    this._Statut = base.CreateQuery<Statut>("[Statut]");
                }
                return this._Statut;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Statut> _Statut;
        /// <summary>
        /// Il n'existe aucun commentaire pour sysdiagrams dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// Il n'existe aucun commentaire pour Encodage dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToEncodage(Encodage encodage)
        {
            base.AddObject("Encodage", encodage);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMessage(Message message)
        {
            base.AddObject("Message", message);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageEnvoi dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMessageEnvoi(MessageEnvoi messageEnvoi)
        {
            base.AddObject("MessageEnvoi", messageEnvoi);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageRecu dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMessageRecu(MessageRecu messageRecu)
        {
            base.AddObject("MessageRecu", messageRecu);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Statut dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToStatut(Statut statut)
        {
            base.AddObject("Statut", statut);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour sysdiagrams dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBModel.Encodage dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idEncodage
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SMS_DBModel", Name="Encodage")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Encodage : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Encodage.
        /// </summary>
        /// <param name="idEncodage">Valeur initiale de idEncodage.</param>
        /// <param name="libelleEncodage">Valeur initiale de libelleEncodage.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Encodage CreateEncodage(int idEncodage, string libelleEncodage)
        {
            Encodage encodage = new Encodage();
            encodage.idEncodage = idEncodage;
            encodage.libelleEncodage = libelleEncodage;
            return encodage;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idEncodage dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idEncodage
        {
            get
            {
                return this._idEncodage;
            }
            set
            {
                this.OnidEncodageChanging(value);
                this.ReportPropertyChanging("idEncodage");
                this._idEncodage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idEncodage");
                this.OnidEncodageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idEncodage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidEncodageChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidEncodageChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété libelleEncodage dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string libelleEncodage
        {
            get
            {
                return this._libelleEncodage;
            }
            set
            {
                this.OnlibelleEncodageChanging(value);
                this.ReportPropertyChanging("libelleEncodage");
                this._libelleEncodage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("libelleEncodage");
                this.OnlibelleEncodageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _libelleEncodage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlibelleEncodageChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlibelleEncodageChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_Message_Encodage", "Message")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Message> Message
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Message>("SMS_DBModel.FK_Message_Encodage", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Message>("SMS_DBModel.FK_Message_Encodage", "Message", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBModel.Message dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idMessage
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SMS_DBModel", Name="Message")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Message : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Message.
        /// </summary>
        /// <param name="idMessage">Valeur initiale de idMessage.</param>
        /// <param name="messageTexte">Valeur initiale de messageTexte.</param>
        /// <param name="messagePDU">Valeur initiale de messagePDU.</param>
        /// <param name="accuseReception">Valeur initiale de accuseReception.</param>
        /// <param name="noDestinataire">Valeur initiale de noDestinataire.</param>
        /// <param name="noEmetteur">Valeur initiale de noEmetteur.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Message CreateMessage(int idMessage, string messageTexte, string messagePDU, int accuseReception, string noDestinataire, string noEmetteur)
        {
            Message message = new Message();
            message.idMessage = idMessage;
            message.messageTexte = messageTexte;
            message.messagePDU = messagePDU;
            message.accuseReception = accuseReception;
            message.noDestinataire = noDestinataire;
            message.noEmetteur = noEmetteur;
            return message;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idMessage dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idMessage
        {
            get
            {
                return this._idMessage;
            }
            set
            {
                this.OnidMessageChanging(value);
                this.ReportPropertyChanging("idMessage");
                this._idMessage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idMessage");
                this.OnidMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idMessage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMessageChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMessageChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété messageTexte dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string messageTexte
        {
            get
            {
                return this._messageTexte;
            }
            set
            {
                this.OnmessageTexteChanging(value);
                this.ReportPropertyChanging("messageTexte");
                this._messageTexte = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("messageTexte");
                this.OnmessageTexteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _messageTexte;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmessageTexteChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmessageTexteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété messagePDU dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string messagePDU
        {
            get
            {
                return this._messagePDU;
            }
            set
            {
                this.OnmessagePDUChanging(value);
                this.ReportPropertyChanging("messagePDU");
                this._messagePDU = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("messagePDU");
                this.OnmessagePDUChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _messagePDU;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmessagePDUChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmessagePDUChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété accuseReception dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int accuseReception
        {
            get
            {
                return this._accuseReception;
            }
            set
            {
                this.OnaccuseReceptionChanging(value);
                this.ReportPropertyChanging("accuseReception");
                this._accuseReception = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("accuseReception");
                this.OnaccuseReceptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _accuseReception;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnaccuseReceptionChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnaccuseReceptionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété noDestinataire dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string noDestinataire
        {
            get
            {
                return this._noDestinataire;
            }
            set
            {
                this.OnnoDestinataireChanging(value);
                this.ReportPropertyChanging("noDestinataire");
                this._noDestinataire = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("noDestinataire");
                this.OnnoDestinataireChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _noDestinataire;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnoDestinataireChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnoDestinataireChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété noEmetteur dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string noEmetteur
        {
            get
            {
                return this._noEmetteur;
            }
            set
            {
                this.OnnoEmetteurChanging(value);
                this.ReportPropertyChanging("noEmetteur");
                this._noEmetteur = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("noEmetteur");
                this.OnnoEmetteurChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _noEmetteur;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnoEmetteurChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnoEmetteurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Encodage dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_Message_Encodage", "Encodage")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Encodage Encodage
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Encodage>("SMS_DBModel.FK_Message_Encodage", "Encodage").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Encodage>("SMS_DBModel.FK_Message_Encodage", "Encodage").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Encodage dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Encodage> EncodageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Encodage>("SMS_DBModel.FK_Message_Encodage", "Encodage");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Encodage>("SMS_DBModel.FK_Message_Encodage", "Encodage", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Statut dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_Message_Statut", "Statut")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Statut Statut
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Statut>("SMS_DBModel.FK_Message_Statut", "Statut").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Statut>("SMS_DBModel.FK_Message_Statut", "Statut").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Statut dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Statut> StatutReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Statut>("SMS_DBModel.FK_Message_Statut", "Statut");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Statut>("SMS_DBModel.FK_Message_Statut", "Statut", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageEnvoi dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_MessageEnvoi_Message", "MessageEnvoi")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MessageEnvoi MessageEnvoi
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MessageEnvoi>("SMS_DBModel.FK_MessageEnvoi_Message", "MessageEnvoi").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MessageEnvoi>("SMS_DBModel.FK_MessageEnvoi_Message", "MessageEnvoi").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageEnvoi dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MessageEnvoi> MessageEnvoiReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MessageEnvoi>("SMS_DBModel.FK_MessageEnvoi_Message", "MessageEnvoi");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MessageEnvoi>("SMS_DBModel.FK_MessageEnvoi_Message", "MessageEnvoi", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageRecu dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_MessageRecu_Message", "MessageRecu")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MessageRecu MessageRecu
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MessageRecu>("SMS_DBModel.FK_MessageRecu_Message", "MessageRecu").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MessageRecu>("SMS_DBModel.FK_MessageRecu_Message", "MessageRecu").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour MessageRecu dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MessageRecu> MessageRecuReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MessageRecu>("SMS_DBModel.FK_MessageRecu_Message", "MessageRecu");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MessageRecu>("SMS_DBModel.FK_MessageRecu_Message", "MessageRecu", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBModel.MessageEnvoi dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idMessage
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SMS_DBModel", Name="MessageEnvoi")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MessageEnvoi : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet MessageEnvoi.
        /// </summary>
        /// <param name="idMessage">Valeur initiale de idMessage.</param>
        /// <param name="dateDemande">Valeur initiale de dateDemande.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static MessageEnvoi CreateMessageEnvoi(int idMessage, global::System.DateTime dateDemande)
        {
            MessageEnvoi messageEnvoi = new MessageEnvoi();
            messageEnvoi.idMessage = idMessage;
            messageEnvoi.dateDemande = dateDemande;
            return messageEnvoi;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idMessage dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idMessage
        {
            get
            {
                return this._idMessage;
            }
            set
            {
                this.OnidMessageChanging(value);
                this.ReportPropertyChanging("idMessage");
                this._idMessage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idMessage");
                this.OnidMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idMessage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMessageChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMessageChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dureeValidite dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> dureeValidite
        {
            get
            {
                return this._dureeValidite;
            }
            set
            {
                this.OndureeValiditeChanging(value);
                this.ReportPropertyChanging("dureeValidite");
                this._dureeValidite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dureeValidite");
                this.OndureeValiditeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _dureeValidite;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndureeValiditeChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndureeValiditeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateDemande dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime dateDemande
        {
            get
            {
                return this._dateDemande;
            }
            set
            {
                this.OndateDemandeChanging(value);
                this.ReportPropertyChanging("dateDemande");
                this._dateDemande = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateDemande");
                this.OndateDemandeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _dateDemande;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateDemandeChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateDemandeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateEnvoi dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> dateEnvoi
        {
            get
            {
                return this._dateEnvoi;
            }
            set
            {
                this.OndateEnvoiChanging(value);
                this.ReportPropertyChanging("dateEnvoi");
                this._dateEnvoi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateEnvoi");
                this.OndateEnvoiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateEnvoi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateEnvoiChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateEnvoiChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_MessageEnvoi_Message", "Message")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Message Message
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Message>("SMS_DBModel.FK_MessageEnvoi_Message", "Message").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Message>("SMS_DBModel.FK_MessageEnvoi_Message", "Message").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Message> MessageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Message>("SMS_DBModel.FK_MessageEnvoi_Message", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Message>("SMS_DBModel.FK_MessageEnvoi_Message", "Message", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBModel.MessageRecu dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idMessage
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SMS_DBModel", Name="MessageRecu")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MessageRecu : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet MessageRecu.
        /// </summary>
        /// <param name="idMessage">Valeur initiale de idMessage.</param>
        /// <param name="dateReception">Valeur initiale de dateReception.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static MessageRecu CreateMessageRecu(int idMessage, global::System.DateTime dateReception)
        {
            MessageRecu messageRecu = new MessageRecu();
            messageRecu.idMessage = idMessage;
            messageRecu.dateReception = dateReception;
            return messageRecu;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idMessage dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idMessage
        {
            get
            {
                return this._idMessage;
            }
            set
            {
                this.OnidMessageChanging(value);
                this.ReportPropertyChanging("idMessage");
                this._idMessage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idMessage");
                this.OnidMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idMessage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMessageChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMessageChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateReception dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime dateReception
        {
            get
            {
                return this._dateReception;
            }
            set
            {
                this.OndateReceptionChanging(value);
                this.ReportPropertyChanging("dateReception");
                this._dateReception = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateReception");
                this.OndateReceptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _dateReception;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateReceptionChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateReceptionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateLecture dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> dateLecture
        {
            get
            {
                return this._dateLecture;
            }
            set
            {
                this.OndateLectureChanging(value);
                this.ReportPropertyChanging("dateLecture");
                this._dateLecture = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateLecture");
                this.OndateLectureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateLecture;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateLectureChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateLectureChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_MessageRecu_Message", "Message")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Message Message
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Message>("SMS_DBModel.FK_MessageRecu_Message", "Message").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Message>("SMS_DBModel.FK_MessageRecu_Message", "Message").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Message> MessageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Message>("SMS_DBModel.FK_MessageRecu_Message", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Message>("SMS_DBModel.FK_MessageRecu_Message", "Message", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBModel.Statut dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idStatut
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SMS_DBModel", Name="Statut")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Statut : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Statut.
        /// </summary>
        /// <param name="idStatut">Valeur initiale de idStatut.</param>
        /// <param name="libelleStatut">Valeur initiale de libelleStatut.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Statut CreateStatut(int idStatut, string libelleStatut)
        {
            Statut statut = new Statut();
            statut.idStatut = idStatut;
            statut.libelleStatut = libelleStatut;
            return statut;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idStatut dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idStatut
        {
            get
            {
                return this._idStatut;
            }
            set
            {
                this.OnidStatutChanging(value);
                this.ReportPropertyChanging("idStatut");
                this._idStatut = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idStatut");
                this.OnidStatutChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idStatut;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidStatutChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidStatutChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété libelleStatut dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string libelleStatut
        {
            get
            {
                return this._libelleStatut;
            }
            set
            {
                this.OnlibelleStatutChanging(value);
                this.ReportPropertyChanging("libelleStatut");
                this._libelleStatut = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("libelleStatut");
                this.OnlibelleStatutChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _libelleStatut;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlibelleStatutChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlibelleStatutChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Message dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SMS_DBModel", "FK_Message_Statut", "Message")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Message> Message
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Message>("SMS_DBModel.FK_Message_Statut", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Message>("SMS_DBModel.FK_Message_Statut", "Message", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour SMS_DBModel.sysdiagrams dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SMS_DBModel", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de name.</param>
        /// <param name="principal_id">Valeur initiale de principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de diagram_id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété name dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété principal_id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _principal_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprincipal_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprincipal_idChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété diagram_id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _diagram_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondiagram_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondiagram_idChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété version dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _version;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnversionChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnversionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété definition dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte[] _definition;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndefinitionChanging(byte[] value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndefinitionChanged();
    }
}
