//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SYNOX_SMSModel", "FK_Sms_SmsStatut", "SmsStatut", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Synox.Services.ServiceSMS.Entity.SmsStatut), "Sms", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Synox.Services.ServiceSMS.Entity.Sms), true)]
[assembly: EdmRelationshipAttribute("SYNOX_SMSModel", "FK_Sms_Projet", "Projet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Synox.Services.ServiceSMS.Entity.Projet), "Sms", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Synox.Services.ServiceSMS.Entity.Sms), true)]
[assembly: EdmRelationshipAttribute("SYNOX_SMSModel", "FK_SmsReception_Projet", "Projet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Synox.Services.ServiceSMS.Entity.Projet), "SmsReception", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Synox.Services.ServiceSMS.Entity.SmsReception), true)]
[assembly: EdmRelationshipAttribute("SYNOX_SMSModel", "FK_NumeroGsmProjet_Projet", "Projet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Synox.Services.ServiceSMS.Entity.Projet), "NumeroGsmProjet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Synox.Services.ServiceSMS.Entity.NumeroGsmProjet), true)]

#endregion

namespace Synox.Services.ServiceSMS.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sms> Sms
        {
            get
            {
                if ((_Sms == null))
                {
                    _Sms = base.CreateObjectSet<Sms>("Sms");
                }
                return _Sms;
            }
        }
        private ObjectSet<Sms> _Sms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SmsReception> SmsReception
        {
            get
            {
                if ((_SmsReception == null))
                {
                    _SmsReception = base.CreateObjectSet<SmsReception>("SmsReception");
                }
                return _SmsReception;
            }
        }
        private ObjectSet<SmsReception> _SmsReception;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SmsStatut> SmsStatut
        {
            get
            {
                if ((_SmsStatut == null))
                {
                    _SmsStatut = base.CreateObjectSet<SmsStatut>("SmsStatut");
                }
                return _SmsStatut;
            }
        }
        private ObjectSet<SmsStatut> _SmsStatut;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Projet> Projet
        {
            get
            {
                if ((_Projet == null))
                {
                    _Projet = base.CreateObjectSet<Projet>("Projet");
                }
                return _Projet;
            }
        }
        private ObjectSet<Projet> _Projet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NumeroGsmProjet> NumeroGsmProjet
        {
            get
            {
                if ((_NumeroGsmProjet == null))
                {
                    _NumeroGsmProjet = base.CreateObjectSet<NumeroGsmProjet>("NumeroGsmProjet");
                }
                return _NumeroGsmProjet;
            }
        }
        private ObjectSet<NumeroGsmProjet> _NumeroGsmProjet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSms(Sms sms)
        {
            base.AddObject("Sms", sms);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SmsReception EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSmsReception(SmsReception smsReception)
        {
            base.AddObject("SmsReception", smsReception);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SmsStatut EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSmsStatut(SmsStatut smsStatut)
        {
            base.AddObject("SmsStatut", smsStatut);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjet(Projet projet)
        {
            base.AddObject("Projet", projet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NumeroGsmProjet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNumeroGsmProjet(NumeroGsmProjet numeroGsmProjet)
        {
            base.AddObject("NumeroGsmProjet", numeroGsmProjet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNOX_SMSModel", Name="NumeroGsmProjet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NumeroGsmProjet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NumeroGsmProjet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numeroGsm">Initial value of the NumeroGsm property.</param>
        /// <param name="baseDeDonnes">Initial value of the BaseDeDonnes property.</param>
        /// <param name="dateCreation">Initial value of the DateCreation property.</param>
        /// <param name="suppression">Initial value of the Suppression property.</param>
        /// <param name="push">Initial value of the Push property.</param>
        /// <param name="fonctionName">Initial value of the FonctionName property.</param>
        public static NumeroGsmProjet CreateNumeroGsmProjet(global::System.Int32 id, global::System.String numeroGsm, global::System.String baseDeDonnes, global::System.DateTime dateCreation, global::System.Boolean suppression, global::System.Boolean push, global::System.String fonctionName)
        {
            NumeroGsmProjet numeroGsmProjet = new NumeroGsmProjet();
            numeroGsmProjet.Id = id;
            numeroGsmProjet.NumeroGsm = numeroGsm;
            numeroGsmProjet.BaseDeDonnes = baseDeDonnes;
            numeroGsmProjet.DateCreation = dateCreation;
            numeroGsmProjet.Suppression = suppression;
            numeroGsmProjet.Push = push;
            numeroGsmProjet.FonctionName = fonctionName;
            return numeroGsmProjet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProjetId
        {
            get
            {
                return _ProjetId;
            }
            set
            {
                OnProjetIdChanging(value);
                ReportPropertyChanging("ProjetId");
                _ProjetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjetId");
                OnProjetIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProjetId;
        partial void OnProjetIdChanging(Nullable<global::System.Int32> value);
        partial void OnProjetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NumeroGsm
        {
            get
            {
                return _NumeroGsm;
            }
            set
            {
                OnNumeroGsmChanging(value);
                ReportPropertyChanging("NumeroGsm");
                _NumeroGsm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NumeroGsm");
                OnNumeroGsmChanged();
            }
        }
        private global::System.String _NumeroGsm;
        partial void OnNumeroGsmChanging(global::System.String value);
        partial void OnNumeroGsmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BaseDeDonnes
        {
            get
            {
                return _BaseDeDonnes;
            }
            set
            {
                OnBaseDeDonnesChanging(value);
                ReportPropertyChanging("BaseDeDonnes");
                _BaseDeDonnes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BaseDeDonnes");
                OnBaseDeDonnesChanged();
            }
        }
        private global::System.String _BaseDeDonnes;
        partial void OnBaseDeDonnesChanging(global::System.String value);
        partial void OnBaseDeDonnesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Suppression
        {
            get
            {
                return _Suppression;
            }
            set
            {
                OnSuppressionChanging(value);
                ReportPropertyChanging("Suppression");
                _Suppression = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Suppression");
                OnSuppressionChanged();
            }
        }
        private global::System.Boolean _Suppression;
        partial void OnSuppressionChanging(global::System.Boolean value);
        partial void OnSuppressionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Push
        {
            get
            {
                return _Push;
            }
            set
            {
                OnPushChanging(value);
                ReportPropertyChanging("Push");
                _Push = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Push");
                OnPushChanged();
            }
        }
        private global::System.Boolean _Push;
        partial void OnPushChanging(global::System.Boolean value);
        partial void OnPushChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FonctionName
        {
            get
            {
                return _FonctionName;
            }
            set
            {
                OnFonctionNameChanging(value);
                ReportPropertyChanging("FonctionName");
                _FonctionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FonctionName");
                OnFonctionNameChanged();
            }
        }
        private global::System.String _FonctionName;
        partial void OnFonctionNameChanging(global::System.String value);
        partial void OnFonctionNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_NumeroGsmProjet_Projet", "Projet")]
        public Projet Projet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_NumeroGsmProjet_Projet", "Projet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_NumeroGsmProjet_Projet", "Projet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Projet> ProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_NumeroGsmProjet_Projet", "Projet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Projet>("SYNOX_SMSModel.FK_NumeroGsmProjet_Projet", "Projet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNOX_SMSModel", Name="Projet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Projet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Projet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        public static Projet CreateProjet(global::System.Int32 id, global::System.String nom)
        {
            Projet projet = new Projet();
            projet.Id = id;
            projet.Nom = nom;
            return projet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_Sms_Projet", "Sms")]
        public EntityCollection<Sms> Sms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sms>("SYNOX_SMSModel.FK_Sms_Projet", "Sms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sms>("SYNOX_SMSModel.FK_Sms_Projet", "Sms", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_SmsReception_Projet", "SmsReception")]
        public EntityCollection<SmsReception> SmsReception
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SmsReception>("SYNOX_SMSModel.FK_SmsReception_Projet", "SmsReception");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SmsReception>("SYNOX_SMSModel.FK_SmsReception_Projet", "SmsReception", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_NumeroGsmProjet_Projet", "NumeroGsmProjet")]
        public EntityCollection<NumeroGsmProjet> NumeroGsmProjet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NumeroGsmProjet>("SYNOX_SMSModel.FK_NumeroGsmProjet_Projet", "NumeroGsmProjet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NumeroGsmProjet>("SYNOX_SMSModel.FK_NumeroGsmProjet_Projet", "NumeroGsmProjet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNOX_SMSModel", Name="Sms")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sms : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sms object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numeroGsm">Initial value of the NumeroGsm property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="dateDemande">Initial value of the DateDemande property.</param>
        public static Sms CreateSms(global::System.Int32 id, global::System.String numeroGsm, global::System.String message, global::System.DateTime dateDemande)
        {
            Sms sms = new Sms();
            sms.Id = id;
            sms.NumeroGsm = numeroGsm;
            sms.Message = message;
            sms.DateDemande = dateDemande;
            return sms;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NumeroGsm
        {
            get
            {
                return _NumeroGsm;
            }
            set
            {
                OnNumeroGsmChanging(value);
                ReportPropertyChanging("NumeroGsm");
                _NumeroGsm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NumeroGsm");
                OnNumeroGsmChanged();
            }
        }
        private global::System.String _NumeroGsm;
        partial void OnNumeroGsmChanging(global::System.String value);
        partial void OnNumeroGsmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateDemande
        {
            get
            {
                return _DateDemande;
            }
            set
            {
                OnDateDemandeChanging(value);
                ReportPropertyChanging("DateDemande");
                _DateDemande = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDemande");
                OnDateDemandeChanged();
            }
        }
        private global::System.DateTime _DateDemande;
        partial void OnDateDemandeChanging(global::System.DateTime value);
        partial void OnDateDemandeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateEnvoi
        {
            get
            {
                return _DateEnvoi;
            }
            set
            {
                OnDateEnvoiChanging(value);
                ReportPropertyChanging("DateEnvoi");
                _DateEnvoi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateEnvoi");
                OnDateEnvoiChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateEnvoi;
        partial void OnDateEnvoiChanging(Nullable<global::System.DateTime> value);
        partial void OnDateEnvoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SmsStatutId
        {
            get
            {
                return _SmsStatutId;
            }
            set
            {
                OnSmsStatutIdChanging(value);
                ReportPropertyChanging("SmsStatutId");
                _SmsStatutId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SmsStatutId");
                OnSmsStatutIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SmsStatutId;
        partial void OnSmsStatutIdChanging(Nullable<global::System.Int32> value);
        partial void OnSmsStatutIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProjetId
        {
            get
            {
                return _ProjetId;
            }
            set
            {
                OnProjetIdChanging(value);
                ReportPropertyChanging("ProjetId");
                _ProjetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjetId");
                OnProjetIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProjetId;
        partial void OnProjetIdChanging(Nullable<global::System.Int32> value);
        partial void OnProjetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RouteurMsgId
        {
            get
            {
                return _RouteurMsgId;
            }
            set
            {
                OnRouteurMsgIdChanging(value);
                ReportPropertyChanging("RouteurMsgId");
                _RouteurMsgId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RouteurMsgId");
                OnRouteurMsgIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RouteurMsgId;
        partial void OnRouteurMsgIdChanging(Nullable<global::System.Int32> value);
        partial void OnRouteurMsgIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_Sms_SmsStatut", "SmsStatut")]
        public SmsStatut SmsStatut
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SmsStatut>("SYNOX_SMSModel.FK_Sms_SmsStatut", "SmsStatut").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SmsStatut>("SYNOX_SMSModel.FK_Sms_SmsStatut", "SmsStatut").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SmsStatut> SmsStatutReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SmsStatut>("SYNOX_SMSModel.FK_Sms_SmsStatut", "SmsStatut");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SmsStatut>("SYNOX_SMSModel.FK_Sms_SmsStatut", "SmsStatut", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_Sms_Projet", "Projet")]
        public Projet Projet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_Sms_Projet", "Projet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_Sms_Projet", "Projet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Projet> ProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_Sms_Projet", "Projet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Projet>("SYNOX_SMSModel.FK_Sms_Projet", "Projet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNOX_SMSModel", Name="SmsReception")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SmsReception : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SmsReception object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numeroGsm">Initial value of the NumeroGsm property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="dateReception">Initial value of the DateReception property.</param>
        public static SmsReception CreateSmsReception(global::System.Int32 id, global::System.String numeroGsm, global::System.String message, global::System.DateTime dateReception)
        {
            SmsReception smsReception = new SmsReception();
            smsReception.Id = id;
            smsReception.NumeroGsm = numeroGsm;
            smsReception.Message = message;
            smsReception.DateReception = dateReception;
            return smsReception;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NumeroGsm
        {
            get
            {
                return _NumeroGsm;
            }
            set
            {
                OnNumeroGsmChanging(value);
                ReportPropertyChanging("NumeroGsm");
                _NumeroGsm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NumeroGsm");
                OnNumeroGsmChanged();
            }
        }
        private global::System.String _NumeroGsm;
        partial void OnNumeroGsmChanging(global::System.String value);
        partial void OnNumeroGsmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateReception
        {
            get
            {
                return _DateReception;
            }
            set
            {
                OnDateReceptionChanging(value);
                ReportPropertyChanging("DateReception");
                _DateReception = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateReception");
                OnDateReceptionChanged();
            }
        }
        private global::System.DateTime _DateReception;
        partial void OnDateReceptionChanging(global::System.DateTime value);
        partial void OnDateReceptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateLecture
        {
            get
            {
                return _DateLecture;
            }
            set
            {
                OnDateLectureChanging(value);
                ReportPropertyChanging("DateLecture");
                _DateLecture = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLecture");
                OnDateLectureChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateLecture;
        partial void OnDateLectureChanging(Nullable<global::System.DateTime> value);
        partial void OnDateLectureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentaire
        {
            get
            {
                return _Commentaire;
            }
            set
            {
                OnCommentaireChanging(value);
                ReportPropertyChanging("Commentaire");
                _Commentaire = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentaire");
                OnCommentaireChanged();
            }
        }
        private global::System.String _Commentaire;
        partial void OnCommentaireChanging(global::System.String value);
        partial void OnCommentaireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProjetId
        {
            get
            {
                return _ProjetId;
            }
            set
            {
                OnProjetIdChanging(value);
                ReportPropertyChanging("ProjetId");
                _ProjetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjetId");
                OnProjetIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProjetId;
        partial void OnProjetIdChanging(Nullable<global::System.Int32> value);
        partial void OnProjetIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_SmsReception_Projet", "Projet")]
        public Projet Projet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_SmsReception_Projet", "Projet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_SmsReception_Projet", "Projet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Projet> ProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projet>("SYNOX_SMSModel.FK_SmsReception_Projet", "Projet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Projet>("SYNOX_SMSModel.FK_SmsReception_Projet", "Projet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNOX_SMSModel", Name="SmsStatut")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SmsStatut : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SmsStatut object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        public static SmsStatut CreateSmsStatut(global::System.Int32 id, global::System.String nom)
        {
            SmsStatut smsStatut = new SmsStatut();
            smsStatut.Id = id;
            smsStatut.Nom = nom;
            return smsStatut;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNOX_SMSModel", "FK_Sms_SmsStatut", "Sms")]
        public EntityCollection<Sms> Sms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sms>("SYNOX_SMSModel.FK_Sms_SmsStatut", "Sms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sms>("SYNOX_SMSModel.FK_Sms_SmsStatut", "Sms", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
