//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synox.Services.ServiceSMS.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synox.Services.ServiceSMS.Entity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_NouveauSmsAEnvoyer.
        /// </summary>
        internal static string SP_NouveauSmsAEnvoyer {
            get {
                return ResourceManager.GetString("SP_NouveauSmsAEnvoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_NouveauSmsRecu.
        /// </summary>
        internal static string SP_NouveauSmsRecu {
            get {
                return ResourceManager.GetString("SP_NouveauSmsRecu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_RecupereSmsEnAttenteEnvoi.
        /// </summary>
        internal static string SP_RecupereSmsEnAttenteEnvoi {
            get {
                return ResourceManager.GetString("SP_RecupereSmsEnAttenteEnvoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_RecupereSmsEnErreur.
        /// </summary>
        internal static string SP_RecupereSmsEnErreur {
            get {
                return ResourceManager.GetString("SP_RecupereSmsEnErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SmsEnvoyes.
        /// </summary>
        internal static string SP_SmsEnvoyes {
            get {
                return ResourceManager.GetString("SP_SmsEnvoyes", resourceCulture);
            }
        }
    }
}
